name: primeira-pipeline
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  primero-job:
    name: "Meu primeiro Job"
    runs-on: ubuntu-latest
    steps:
      - name: "Primeira Ação"
        run: echo "Hello world!!!"
      - name: "Segunda Ação"
        run: |
          echo "Você criou sua primeiro workflow"
          echo "Parabéns!!!"
      - name: "Script python"
        run: |
          variavel = "Hellow Python!!!"
          print(variavel)
        shell: python
  segundo-job:
    name: "Segundo JOB- atualização Node js"
    runs-on: ubuntu-latest
    needs: [primero-job]
    steps: 
      - name: "verifica versão"
        run: node --version
      - name: "Define versão node"
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '20.13.1'
      - name: "Verifica nova versão"
        run: node --version
    
        
